### ISSUE TITLE
Typescript file issues

### ISSUE THREAD

**Issue by dgwaldo** [Esri/Terraformer#296] opened 2017-03-06 22:55 UTC
It seems like the typings file should be named index.d.ts and then you don't need to include a types: node in the package.json.  Otherwise a types node is needed.  Also, I believe a handful of exports are needed in the .t.ds definition files.  Currently the module isn't exporting anything.

**Comment by jgravois** [comment] 2017-03-06 23:33
@JeffJacobson you see any problem with renaming `terraformer-*.d.ts` to `index.d.ts`?

> Currently the module isn't exporting anything.

is it not sufficient that `Terraformer` is exported?

```js
// https://github.com/Esri/Terraformer/blob/5d95b47f99d5fa12eda7d73ff2015cc08152df5d/terraformer.d.ts#L158
export = Terraformer;
```

**Comment by dgwaldo** [comment] 2017-03-07 00:12
I guess it is sufficient that it's exported, I didn't realize that export is inferred inside namespace declarations.

**Comment by JeffJacobson** [comment] 2017-03-07 21:15
It's been a while since I've looked at this. I'll take a look at it and get back to you...

In general, I can only get the TypeScript compiler to automatically pick up type definitions from an NPM module when the [module resolution setting](http://www.typescriptlang.org/docs/handbook/module-resolution.html#node) is set to "node", as in the example tsconfig.json below.

```json
{
    "compilerOptions": {
        "module": "amd",
        "target": "es5",
        "noImplicitAny": true,
        "strictNullChecks": true,
        "sourceMap": false,
        "lib": [
            "dom",
            "es5",
            "es2015.collection",
            "es2015.promise"
        ],
        "moduleResolution": "node"
    },
    "include": [
        "./app/*"
    ],
    "exclude": [
        "node_modules"
    ]
}
```

**Comment by JeffJacobson** [comment] 2017-03-07 21:33
I can reproduce the issue. Working on resolving it...

**Closed** 2017-03-10 19:31 UTC

**Comment by jgravois** [comment] 2017-03-10 19:33
@JeffJacobson was gracious enough to contribute a fix for this issue.

@dgwaldo can you use `master` to confirm that you have everything you need. i'm happy to cut a patch release afterward if it'd be helpful.

**Comment by dgwaldo** [comment] 2017-03-16 04:55
Been a busy week but I hope to pull it in this weekend...

**Comment by jgravois** [comment] 2017-03-29 22:33
@darcyparker has pointed out that its best if the library itself and typings file share the same name.

@dgwaldo if/when you ever take a look at the way things are set up in `master` now, we'd be happy to assist if you have trouble.

**Comment by dgwaldo** [comment] 2017-04-20 15:12
Finally got a chance to look at this again. 
In package.json I've updated the dependencies to look at the latest from github.
` "dependencies": {
    "terraformer": "git+https://github.com/Esri/Terraformer.git",
    "terraformer-arcgis-parser": "git+https://github.com/Esri/terraformer-arcgis-parser.git",
  },`
 
Either of the following import styles now seem to work.
`import * as Terraformer from "terraformer";`
or 
`import Terraformer = require("terraformer");`

I'm also importing TerraformerArcGIS as follows.

`import * TerraformerArcGIS from "terraformer-arcgis-parser";`

In the code I'm then utilizing them like this.  
`let primitive = new Terraformer.FeatureCollection(geojson);
 let arcGisJson = new TerraformerArcGIS.convert(primitive);`

It might be helpful to include something on how to import the library when using typescript.   
Thanks!
